### ISSUE TITLE
Text labels on x axis tickmarks

### ISSUE THREAD

**Issue by dorlandode** [n3-charts/line-chart#264] opened 2015-06-23 15:02 UTC
I have been trying to show a label on the x axis instead of the data point value. For example, say I want to show a country name instead of a numeric value.  I have been playing with the labelFunction on the x axis, but so far have been unsuccessful.

http://codepen.io/anon/pen/oXozrM

My hope was that the parameter on the labelFunction would be the data object with its respective object properties.  What is the best way to accomplish what I am trying to do.

**Comment by chaosmail** [comment] 2015-06-23 15:25
Hi @dorlandode 

We are parsing the data array to the internal format, that's why you cannot access these properties. You could extract the labels from the data and use the index argument to access it. Here is an example: [http://codepen.io/anon/pen/ZGaBOJ](http://codepen.io/anon/pen/ZGaBOJ)

Let me know if this helps you!

Best,
Christoph

**Comment by dorlandode** [comment] 2015-06-23 21:15
Thanks for the example, that worked great.  I tweaked it a bit.

http://codepen.io/anon/pen/LVOypB

Is there a reason not to do it like this.

**Comment by chaosmail** [comment] 2015-06-24 07:13
It's absolutely fine; however under the hood we insert an additional 0 element to shift the first column to the right - so you would have to use `i-1`.

Here is an updated version of your example: [http://codepen.io/anon/pen/qdVPdK](http://codepen.io/anon/pen/qdVPdK) where I also added some cool styling options.

I will close this issue as I think the problem is solved. Let me know if you have any further questions!

Best,
Christoph

**Closed by chaosmail** 2015-06-24 07:13 UTC

**Comment by nitin9291** [comment] 2017-04-28 07:34
i am fairly new to this , but the codepen is not working , am i missing something here

**Comment by chaosmail** [comment] 2017-04-28 16:02
This was an old version. Here is a working example http://codepen.io/chaosmail/pen/VbpyNQ

**Comment by test9291** [comment] 2017-05-01 18:09
thank you for the help

**Comment by test9291** [comment] 2017-05-02 04:21
one more question,if i have data less than 8 element in json data the chart wont work.  why is that?

**Comment by test9291** [comment] 2017-05-02 07:27
nevermind, silly of me,had to set tick ... :-p

**Comment by ghost** [comment] 2017-07-03 00:45
is there a way to implement stacked bar chart in n3linechart?
