### ISSUE TITLE
Tooltips set to none causes "TypeError: svgTextElement is null"

### ISSUE THREAD

**Issue by Arkh1** [n3-charts/line-chart#188] opened 2015-01-22 21:59 UTC
When you hover over chart columns with tooltips set to none you get a flood of "TypeError: svgTextElement is null" errors in the console.

This is also caused by setting the type of the chart to thumbnail (I am assuming since it is setting the tooltip mode to "none")

Would be nice to be able to use these features without getting a flood of errors.

As a side note...  This can be reproduced in the n3-chart playground.
http://n3-charts.github.io/line-chart/#/

**Comment by lorem--ipsum** [comment] 2015-05-23 00:55
Duplicate of #208.

**Closed by lorem--ipsum** 2015-05-23 00:55 UTC
