### ISSUE TITLE
n3-charts and injectors

### ISSUE THREAD

**Issue by gwenaellarmet** [n3-charts/line-chart#429] opened 2016-02-10 14:58 UTC
I'm trying to add n3-charts to my curent angular project and i'm having trouble getting it injected by gulp or grunt.
So far I tried :

1. install n3-charts with npm install as recommended
2. install n3-charts with bower to get the src and make a build of it
3. tried again 1 and 2 on a new clean project generated by : https://github.com/Swiip/generator-gulp-angular

I put the module as a dependency
`  angular.module('xxxx', [ 'n3-line-chart' ]);`

```
I always get the same error :
ncaught Error: [$injector:modulerr] Failed to instantiate module xxxx due to:
Error: [$injector:modulerr] Failed to instantiate module n3-line-chart due to:
Error: [$injector:nomod] Module 'n3-line-chart' is not available! 
```

Any idea how to get n3-chart to work on my project ?

**Comment by lorem--ipsum** [comment] 2016-02-21 09:38
Have you added the JavaScript file to your HTML file ?

**Comment by gwenaellarmet** [comment] 2016-02-21 14:09
Yes indeed, but I wish I could avoid putting the link in my html file and let my injector do the work.
Could you make a bower package alongside the npm package ? I think It would resolve my issue in no time.

**Comment by lorem--ipsum** [comment] 2016-02-21 15:52
Well even with a bower package you'd still have to include the script file.

**Comment by gwenaellarmet** [comment] 2016-02-21 16:54
I have included the script file but it still doesn't work.
You can try with the generator I linked you should get the same result as I did

**Comment by UCKFA** [comment] 2016-02-24 09:50
I have the same problem. It doesn't load the files in the 'node_modules' directory after installing with npm, and if I do it manually, the error remains the same, but the files are loaded.

**Comment by UCKFA** [comment] 2016-02-26 12:05
I would like to share with you my solution. I moved the n3-charts folder to the bower_components folder. The problem is that the files are not loaded from the node_modules folder.

**Comment by lorem--ipsum** [comment] 2016-02-27 12:36
If you install something with npm, you shouldn't be looking for it in the bower_components folders...

**Comment by chaosmail** [comment] 2016-03-26 12:51
Hi @UCKFA 
hope you found a temporary solution for your problem. I will close this now and you can follow the status of bower support here #438.
Best,
Christoph

**Closed by chaosmail** 2016-03-26 12:51 UTC
